# Generated by Django 6.0.2 on 2026-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
