# Generated by Django 6.0.2 on 2026-02-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
