# Generated by Django 6.0.2 on 2026-02-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("jobs", "0002_jobdescription_embedding"),
        ("resumes", "0002_resume_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.jobdescription"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resumes.resume"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="suggestions",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="analysis",
            unique_together={("resume", "job")},
        ),
    ]
